

# This file was *autogenerated* from the file 25.sage
from sage.all_cmdline import *   # import sage library

_sage_const_20201227 = Integer(20201227); _sage_const_7 = Integer(7); _sage_const_1 = Integer(1)
pubkeys = []

R = Integers(_sage_const_20201227 )
pubkeys.append(R(input()))
pubkeys.append(R(input()))
print(pubkeys)

secrets = [discrete_log(pubkey, R(_sage_const_7 )) for pubkey in pubkeys]
private_keys = [pubkey ** secret for pubkey, secret in zip(pubkeys, secrets[::-_sage_const_1 ])]
print(secrets)
print(private_keys)

